Controllers/AppController.cs
using DutchTreatEmpty.Data;
using DutchTreatEmpty.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DutchTreatEmpty.Controllers
{
    public class AppController : Controller
    {
        private readonly ILogger<AppController> logger;
        private readonly IDutchRepository repository;

        public AppController(ILogger<AppController> _logger,
            IDutchRepository repository)
        {
            logger = _logger;
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Send email
            }
            else
            {
                //Send Error
            }

            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Shop()
        {
            var products = repository.GetAllProducts();
            return View(products);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat:  @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    @RenderSection("head", false)
</head>
<body>
    <header class="container-fluid">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand"><i class="fas fa-paint-brush"></i> Dutch Treat</h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Home</a></li>
                    <li><a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li><a class="nav-link" asp-controller="App" asp-action="About">About</a></li>
                    <li><a class="nav-link" asp-controller="App" asp-action="Shop">Shop</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a class="nav-link" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">Copy right 2021</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>